# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Fomento Brasil
email: contato@fomentobrasil.com.br
description: > # this means to ignore newlines until "baseurl:"
  Portal sobre Factoring mais completo do Brasil. Informações sobre o que é
  Fomento Comercial, como abrir uma factoring, softwares e sistemas para factoring,
  franquias e últimas noticías do setor.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.fomentobrasil.com.br" # the base hostname & protocol for your site
facebook_app_id: 138847736581737

# Build settings
markdown: kramdown
